### ISSUE TITLE
Installation manual is missing a few steps

### ISSUE THREAD

**Issue by AriaanBruinsma** [siemen6/Screenshot-CMS#5]
Installation manual is missing a few steps, we've figured it out eventually, but it took me a bit, since I'm not that familiar with Laravel.

- The "storage" and "bootstrap/cache" directories need at least 770 perms.

- Also there was one missing symlink, that should be created by Artisan with the following command:
`php artisan storage:link`

- perhaps a list of minimum requirements of the Apache2 vhost could also shave some time of, since Laravels routing (like most frameworks) heavily depends on mod_rewrite. Like:
`RewriteEngine on`
`Options +FollowSymLinks`
`AllowOverride All`

Please keep going, this app looks really nice 👍

**Comment by siemen6** [comment]
Hi Ariaan,

I rewrited the installation manual.
If there is anything else I can help you with feel free to open a new issue.

Closed.
